AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 2
  Api:
    OpenApiVersion: 3.0.2
Resources:
  UniLambdaBasicApi:  # API Gatewayの設定
    Type: AWS::Serverless::Api
    Properties:
      Name: ApigwSamDeployTypescript # 設置するリソース名（任意）
      StageName: dev
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'WWW-Authenticate'"
              Access-Control-Allow-Origin: "'*'"
  UniPingFunc: # Lambdaの設定
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PingLambdaSamDeployTypescript # 設置するリソース名（任意）
      Runtime: python3.8 # 利用するランタイム
      Role: arn:aws:iam::328544716089:role/lambda-deploy-role # 手順2で作ったIAMロール
      CodeUri: ../../../built/dev/ping # Lambda関数が置いてあるファイルパス
      Handler: index.handler # Lambda関数の ${ファイル名.メソッド名}
      MemorySize: 128
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /ping # Lambdaを実行するパス
            Method: get
            RestApiId: !Ref UniLambdaBasicApi # 紐付けるAPI Gateway
